# Generated by Django 3.2.6 on 2021-08-11 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.IntegerField()),
                ('month', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='picture')),
            ],
        ),
    ]
